package ogla.axischart3D.gui;

import ogla.axischart.lists.ListListener;
import ogla.axischart.lists.ListsContainer;
import ogla.axischart.util.DefaultDisplayingStackImpl;
import ogla.axischart.util.CheckList;
import ogla.core.util.ListElementManager;
import ogla.axischart3D.AxisChart3D;
import ogla.axischart3D.lists.ListAxisChart3DComponentBundle;
import ogla.axischart3D.lists.ListAxisChart3DInstalledComponent;
import ogla.axischart3D.plugin.chartcomponent.AxisChart3DComponent;
import ogla.axischart3D.plugin.chartcomponent.AxisChart3DComponentBundle;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ComponentsPanel extends javax.swing.JPanel {

    protected AxisChart3D axisChart;
    protected DefaultDisplayingStackImpl displayStackImpl;
    protected ListsContainer listsContainer;
    private ListAxisChart3DComponentBundle listAxisChart3DComponentBundle = null;
    private ListAxisChart3DInstalledComponent listAxisChart3DInstalledComponent = null;
    protected DefaultListModel defaultListModel = new DefaultListModel();
    protected DefaultListModel defaultListModel1 = new DefaultListModel();

    private class ListListener1 implements ListListener<AxisChart3DComponentBundle> {

        private DefaultListModel defaultListModel;

        public ListListener1(DefaultListModel defaultListModel) {
            this.defaultListModel = defaultListModel;
        }

        public void isAdded(AxisChart3DComponentBundle t) {
            defaultListModel.addElement(ListElementManager.register(t));
        }

        public void isRemoved(AxisChart3DComponentBundle t) {
            defaultListModel.removeElementAt(ListElementManager.getIndex(t, defaultListModel));
        }
    }

    private class ListListener2 implements ListListener<AxisChart3DComponent> {

        private DefaultListModel defaultListModel;

        public ListListener2(DefaultListModel defaultListModel) {
            this.defaultListModel = defaultListModel;
        }

        public void isAdded(AxisChart3DComponent t) {
            defaultListModel.addElement(new CheckList.Element(t, t.getBundle().getLabel()));
            // axisChart.shouldBeRendered();
            // axisChart.repaintChartSurface();
        }

        public void isRemoved(AxisChart3DComponent t) {
            for (int fa = 0; fa < defaultListModel.size(); fa++) {
                CheckList.Element element = (CheckList.Element) defaultListModel.get(fa);
                AxisChart3DComponent comp = (AxisChart3DComponent) element.getObject();
                if (comp.equals(t)) {
                    //       disactivate(t, fa);
                }
            }
            final int index = ListElementManager.getIndex(t, defaultListModel);
            defaultListModel.removeElementAt(index);
            // axisChart.shouldBeRendered();
            //  axisChart.repaintChartSurface();
        }
    }

    /** Creates new form ChartComponentsPanel */
    public ComponentsPanel(AxisChart3D axisChart, ListsContainer listsContainer, DefaultDisplayingStackImpl displayStackImpl) {
        initComponents();
        this.axisChart = axisChart;
        this.listsContainer = listsContainer;
        this.listAxisChart3DComponentBundle = listsContainer.get(ListAxisChart3DComponentBundle.class);
        this.listAxisChart3DInstalledComponent = listsContainer.get(ListAxisChart3DInstalledComponent.class);
        this.displayStackImpl = displayStackImpl;
        jList1.setModel(defaultListModel);
        jList2.setModel(defaultListModel1);
        listAxisChart3DComponentBundle.addListListener(new ListListener1(defaultListModel));
        listAxisChart3DInstalledComponent.addListListener(new ListListener2(defaultListModel1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButtonRemove = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(577, 210));
        setRequestFocusEnabled(false);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Attached components"));

        jList2.setCellRenderer(new CheckList());
        jScrollPane2.setViewportView(jList2);

        jButtonRemove.setText("remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonAdd.setText("add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("All components"));

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jButtonAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonRemove))
                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        jButton4.setText("Configure");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton4)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int[] indices = jList1.getSelectedIndices();
        for (int index : indices) {
            AxisChart3DComponent chartComponent = this.listAxisChart3DComponentBundle.get(index).newAxisChart3DComponent();
            this.listAxisChart3DInstalledComponent.add(chartComponent);
            chartComponent.attachTo(axisChart);
        }

}//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        int[] indices = jList2.getSelectedIndices();
        for (int index : indices) {
            AxisChart3DComponent chartComponent = listAxisChart3DInstalledComponent.get(index);
            listAxisChart3DInstalledComponent.remove(chartComponent);
        }

}//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        int index = jList2.getSelectedIndex();
        if (index == -1) {
            return;
        }
        AxisChart3DComponent component = listAxisChart3DInstalledComponent.get(index);
        JFrame jFrame = component.getFrame();
        if (jFrame != null) {
            jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            jFrame.addWindowListener(new WindowListenerImpl(jFrame));
            jFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "This component doesn't have any configuration panel.");
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private class WindowListenerImpl implements WindowListener {

        public WindowListenerImpl(JFrame jFrame) {
            this.jFrame = jFrame;
        }
        JFrame jFrame;

        public void windowOpened(WindowEvent e) {
        }

        public void windowClosing(WindowEvent e) {
        }

        public void windowClosed(WindowEvent e) {
            jFrame.removeWindowListener(this);
        }

        public void windowIconified(WindowEvent e) {
        }

        public void windowDeiconified(WindowEvent e) {
        }

        public void windowActivated(WindowEvent e) {
        }

        public void windowDeactivated(WindowEvent e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
