---
# OS type
os: linux
dist: trusty
sudo: required
language: cpp

# Compiler selection
compiler:
  - gcc

# Install packages
addons:
  apt:
    packages:
    - google-mock
    - libgtest-dev

#safelist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - OAP_PATH=$TRAVIS_BUILD_DIR
    - OAP_GMOCK_PATH=/usr/src/gmock

# Build steps
script:
  - make clean && make TARGET_ARCH=HOST MODE=DebugSanitizer && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oapHostTests && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oap2dt3dTests
  
# Notify after build
notifications:
  email: false

git:
  lfs_skip_smudge: true
