---
# OS type
os: linux
dist: xenial
sudo: required
language: cpp

# Compiler selection
compiler:
  - gcc

# Install packages
addons:
  apt:
    packages:
    - google-mock
    - libgtest-dev

#safelist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - OAP_PATH=$TRAVIS_BUILD_DIR
    - OAP_GMOCK_PATH=/usr/src/gmock
    - OAP_GTEST_PATH=/usr/src/gtest
    - OAP_BUILD_THREADS=1

# Build steps
script:
  - >
     cd scripts && bash download_module_data.sh oapNeural && cd ..
     && make clean && make MODE=DebugSanitizer clean && make MODE=Release clean
     && make TARGET_ARCH=HOST MODE=DebugSanitizer
     && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oapHostTests --gtest_shuffle
     && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oapAppUtilsTests --gtest_shuffle
     && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oapAppUtilsFuncTests --gtest_filter="OapPngFileTests, LoadMnistExamples"
     && ${OAP_PATH}/dist/DebugSanitizer/x86/bin/oapNeuralRoutinesHostTests --gtest_shuffle
     && make TARGET_ARCH=HOST MODE=Release
     && ${OAP_PATH}/dist/Release/x86/bin/oapHostTests --gtest_shuffle
     && ${OAP_PATH}/dist/Release/x86/bin/oapAppUtilsTests --gtest_shuffle
     && ${OAP_PATH}/dist/Release/x86/bin/oapAppUtilsFuncTests --gtest_filter="OapPngFileTests, LoadMnistExamples"
     && ${OAP_PATH}/dist/Release/x86/bin/oapNeuralRoutinesHostTests --gtest_shuffle
  
# Notify after build
notifications:
  email: false

git:
  lfs_skip_smudge: true
