---
# OS type
os: linux
dist: trusty
sudo: required
language: cpp
matrix:
  fast_finish: true

# Compiler selection
compiler:
  - gcc

# Install packages
addons:
  apt:
    packages:
    - google-mock
    - libgtest-dev

#safelist
branches:
  only:
    - master
    - oap2dt3d_development

# Environment variables
env:
  global:
    - OAP_PATH=$TRAVIS_BUILD_DIR
    - GMOCK_DIR=/usr/src/gmock

# Build steps
script:
  - make clean
  - make TARGET_ARCH=HOST
  - ${OAP_PATH}/dist/Debug/x86/bin/oapTestsHost
  - ${OAP_PATH}/dist/Debug/x86/bin/oap2dt3dTests

# Notify after build
notifications:
  email: false
