/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on 2011-10-04, 19:00:40
 */
package ogla.axischart.util;

import ogla.axischart.util.ImageList;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

/**
 *
 * @author marcin
 */
public class ImagePanel extends javax.swing.JPanel {

    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();

    }
    private Image image = null;

    public void setImage(Image image) {
        this.image = image;
    }

    public void setLabel(String label) {
        this.setToolTipText(label);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D gd = (Graphics2D) g;
        int dw = this.getWidth() - ImageList.getWidthToWhichImageIsScaled();
        int dh = this.getWidth() - ImageList.getHeightToWhichImageIsScaled();
        dw = dw / 2;
        dh = dh / 2;
        gd.drawImage(image, dw, dh, ImageList.getWidthToWhichImageIsScaled(),
                ImageList.getHeightToWhichImageIsScaled() - dh, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
