package ogla.axis.gui;

import ogla.axis.util.AxisManager;

public class AxisFrame extends javax.swing.JFrame {

    /** Creates new form HorizontalFrame */
    public AxisFrame() {
        initComponents();
        axisPanel1 = new AxisPanel();

    }

    public void setAxisManager(AxisManager axisManager) {
        axisPanel1.setAxisManager(axisManager);
    }

    public AxisPanel getAxisPanel() {
        return axisPanel1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisPanel1 = new ogla.axis.gui.AxisPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(axisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(axisPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ogla.axis.gui.AxisPanel axisPanel1;
    // End of variables declaration//GEN-END:variables
}
