package ogla.plot.errorpoint;

import ogla.axischart2D.AxisChart2D;
import ogla.axischart2D.plugin.plotmanager.AxisChart2DPlotManager;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class ConfigurationFrame extends javax.swing.JFrame {

    /** Creates new form ConfigurationFrame */
    protected AxisChart2DPlotManager plotManager;
    protected Properties properties;
    private AxisChart2D axisChart;

    public int getIndexErrorX() {
        Number n = (Number) jSpinner4.getValue();
        return n.intValue();
    }

    public int getIndexErrorY() {
        Number n = (Number) jSpinner5.getValue();
        return n.intValue();
    }

    public boolean isNumberX() {
        return jCheckBox1.isSelected();
    }

    public boolean isNumberY() {
        return jCheckBox2.isSelected();
    }

    class CheckBoxsGroup {

        public List<JCheckBox> boxes = new ArrayList<JCheckBox>();
        public HashMap<JCheckBox, Component> components = new HashMap<JCheckBox, Component>();

        public void setSelected(JCheckBox jCheckBox) {
            for (JCheckBox box : boxes) {
                if (box.equals(jCheckBox)) {
                    Component component = components.get(box);
                    if (component != null) {
                        component.setEnabled(true);
                    }
                } else {
                    box.setSelected(false);
                    Component component = components.get(box);
                    if (component != null) {
                        component.setEnabled(false);
                    }
                }
            }
        }
    }
    private CheckBoxsGroup checkBoxsGroup1 = new CheckBoxsGroup();
    private CheckBoxsGroup checkBoxsGroup2 = new CheckBoxsGroup();

    /** Creates new form BundleDataFrameImpl */
    public ConfigurationFrame(AxisChart2D axisChart, AxisChart2DPlotManager plotManager, Properties properties) {
        initComponents();
        this.plotManager = plotManager;
        this.properties = properties;
        this.axisChart = axisChart;

        jColorChooser1.getSelectionModel().addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                ConfigurationFrame.this.properties.setColor(jColorChooser1.getColor());
                ConfigurationFrame.this.axisChart.repaintChartSurface();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jColorChooser1.setColor(new java.awt.Color(1, 1, 1));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel1.setText("width");
        jToolBar1.add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jToolBar1.add(jSpinner1);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        jLabel4.setText("Error X:");
        jToolBar1.add(jLabel4);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        jToolBar1.add(jSpinner4);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Number");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jCheckBox1);
        jToolBar1.add(jSeparator4);

        jLabel5.setText("Error y:");
        jToolBar1.add(jLabel5);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        jToolBar1.add(jSpinner5);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Number");
        jCheckBox2.setFocusable(false);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jCheckBox2);
        jToolBar1.add(jSeparator5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        Number n = (Number) jSpinner1.getValue();
        properties.setStroke(new BasicStroke(n.intValue()));
        axisChart.repaintChartSurface();
}//GEN-LAST:event_jSpinner1StateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
