package ogla.axischart2D.gui;

import ogla.core.data.DataBundle;
import ogla.axischart2D.AxisChart2D;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author marcin
 */
public class RepositoryFrame extends javax.swing.JFrame {

    protected AxisChart2D axisChart;
    protected DataBundle bundleData;
    protected DataPanel panel;

    /** Creates new form RepositoryFrame */
    public RepositoryFrame(AxisChart2D axisChart, DataBundle bundleData, DataPanel panel) {
        initComponents();
        this.axisChart = axisChart;
        this.bundleData = bundleData;
        this.panel = panel;
    }

    public void setBundleData(DataBundle bundleData) {
        this.bundleData = bundleData;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setTitle("Analysis - Tools Frame");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jButton1.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.jPanel != null) {
            this.jPanel.setSize(this.getContentPane().getSize());
        }
    }//GEN-LAST:event_formComponentResized
    private JPanel jPanel = null;


    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b == false) {
            panel.fillList(bundleData);
        }
    }

    public void addPanel(JPanel jPanel) {
        this.getContentPane().removeAll();
        this.getContentPane().add(jPanel, BorderLayout.CENTER);
        jPanel.setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.getContentPane().setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.getContentPane().invalidate();
        this.getContentPane().validate();
        this.validate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
