package ogla.axischart3D.gui;

import ogla.axischart.gui.PicturesFrame;
import ogla.axischart.lists.ListsContainer;
import ogla.axischart3D.AxisChart3D;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author marcin
 */
public final class ChartCanvas extends javax.swing.JPanel {

    protected AxisChart3D axisChart;
    private DefaultListModel defaultListModel = new DefaultListModel();

    public void setLabelRendering() {
        jLabel1.setText("rendering...");
        jLabel1.setVisible(true);
    }

    public void clearLabel() {
        jLabel1.setVisible(false);
    }

    /** Creates new form JChartPanel */
    public ChartCanvas(AxisChart3D axisChart, ListsContainer listsContainer) {
        initComponents();
        this.axisChart = axisChart;
        this.picturesFrame = new PicturesFrame(defaultListModel, axisChart, listsContainer);
        jLabel1.setVisible(false);
        axisChart.setBackground(this.getBackground());
        axisChart.getChartSurface().setSize(jPanel1.getPreferredSize());
        axisChart.getChartSurface().setPreferredSize(jPanel1.getPreferredSize());
        axisChart.getChartSurface().setVisible(true);
        jPanel1.add(axisChart.getChartSurface(), BorderLayout.CENTER);
        jPanel1.setBackground(Color.white);
        this.setBackground(Color.white);
        axisChart.getChartSurface().setBackground(Color.white);
        this.revalidate();
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        jLabel1.setText("rendering...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Save as image");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator7);

        jButton2.setText("Display");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        axisChart.getChartSurface().setSize(jPanel1.getSize());
        axisChart.getChartSurface().setPreferredSize(jPanel1.getSize());
    }//GEN-LAST:event_jPanel1ComponentResized
    PicturesFrame picturesFrame = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        picturesFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private class DisplayPopupMenu extends JPopupMenu {

        JCheckBoxMenuItem item1 = new JCheckBoxMenuItem("ALL");
        JCheckBoxMenuItem item2 = new JCheckBoxMenuItem("GRID");

        public DisplayPopupMenu() {
            this.add(item1);
            item1.setSelected(true);
            item2.setSelected(false);
            item1.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    axisChart.setTypeOfDisplaying(AxisChart3D.Displaying.ALL);
                    item1.setSelected(true);
                    item2.setSelected(false);

                }
            });
            this.add(item2);
            item2.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    axisChart.setTypeOfDisplaying(AxisChart3D.Displaying.GRID);
                    item2.setSelected(true);
                    item1.setSelected(false);

                }
            });
        }
    }
    private DisplayPopupMenu displayPopupMenu = new DisplayPopupMenu();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        displayPopupMenu.show(jButton2, 0, jButton2.getHeight());
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
