package ogla.axis.gui;

import ogla.axis.util.AxisManager;

public class MainFrame extends javax.swing.JFrame {

    /** Creates new form AxisFrame */
    public MainFrame(AxisManager axisManager1, AxisManager axisManager2) {
        initComponents();
        axisPanel1.setAxisManager(axisManager1);
        axisPanel2.setAxisManager(axisManager2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        axisPanel1 = new ogla.axis.gui.AxisPanel();
        axisPanel2 = new ogla.axis.gui.AxisPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        axisPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("X Axis"));

        axisPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Y Axis"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(axisPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axisPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(axisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(axisPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ogla.axis.gui.AxisPanel axisPanel1;
    private ogla.axis.gui.AxisPanel axisPanel2;
    // End of variables declaration//GEN-END:variables
}
