package ogla.axischart2D.gui;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ogla.axischart.lists.ListListener;
import ogla.axischart.lists.ListsContainer;
import ogla.axischart.util.CheckList;
import ogla.axischart.util.DefaultDisplayingStackImpl;
import ogla.axischart2D.AxisChart2D;
import ogla.axischart2D.lists.AxisChart2DComponentBundleList;
import ogla.axischart2D.lists.ListAxisChart2DInstalledComponent;
import ogla.axischart2D.plugin.chartcomponent.AxisChart2DComponent;
import ogla.axischart2D.plugin.chartcomponent.AxisChart2DComponentBundle;
import ogla.core.util.ListElementManager;

public class ComponentsPanel extends javax.swing.JPanel {

    protected AxisChart2D axisChart;
    protected DefaultDisplayingStackImpl displayStackImpl;
    protected ListsContainer listsContainer;
    private AxisChart2DComponentBundleList listChartComponentBundle = null;
    private ListAxisChart2DInstalledComponent listInstalledChartComponent = null;
    protected DefaultListModel defaultListModel = new DefaultListModel();
    protected DefaultListModel defaultListModel1 = new DefaultListModel();

    private class ListListener1 implements ListListener<AxisChart2DComponentBundle> {

        private DefaultListModel defaultListModel;

        public ListListener1(DefaultListModel defaultListModel) {
            this.defaultListModel = defaultListModel;
        }

        public void isAdded(AxisChart2DComponentBundle t) {
            defaultListModel.addElement(ListElementManager.register(t));
        }

        public void isRemoved(AxisChart2DComponentBundle t) {
            defaultListModel.removeElementAt(ListElementManager.getIndex(t, defaultListModel));
        }
    }

    private class ListListener2 implements ListListener<AxisChart2DComponent> {

        private DefaultListModel defaultListModel;

        public ListListener2(DefaultListModel defaultListModel) {
            this.defaultListModel = defaultListModel;
        }

        public void isAdded(AxisChart2DComponent t) {
            defaultListModel.addElement(new CheckList.Element(t, t.getBundle().getLabel()));
            activate(t, defaultListModel.size() - 1);
            axisChart.repaintChartSurface();
        }

        public void isRemoved(AxisChart2DComponent t) {
            for (int fa = 0; fa < defaultListModel.size(); fa++) {
                CheckList.Element element = (CheckList.Element) defaultListModel.get(fa);
                AxisChart2DComponent comp = (AxisChart2DComponent) element.getObject();
                if (comp.equals(t)) {
                    disactivate(t, fa);
                }
            }
            defaultListModel.removeElementAt(ListElementManager.getIndex(t, defaultListModel));
            axisChart.repaintChartSurface();
        }
    }

    /** Creates new form ChartComponentsPanel */
    public ComponentsPanel(AxisChart2D axisChart, ListsContainer listsContainer, DefaultDisplayingStackImpl displayStackImpl) {
        initComponents();
        this.axisChart = axisChart;
        this.listsContainer = listsContainer;
        this.listChartComponentBundle = listsContainer.get(AxisChart2DComponentBundleList.class);
        this.listInstalledChartComponent = listsContainer.get(ListAxisChart2DInstalledComponent.class);
        this.displayStackImpl = displayStackImpl;
        jList1.setModel(defaultListModel);
        jList2.setModel(defaultListModel1);
        listChartComponentBundle.addListListener(new ListListener1(defaultListModel));
        listInstalledChartComponent.addListListener(new ListListener2(defaultListModel1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButtonRemove = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setPreferredSize(new java.awt.Dimension(577, 210));
        setRequestFocusEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Component"));

        jButton4.setText("Configure");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Disactive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Active");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Attached components"));

        jList2.setCellRenderer(new CheckList());
        jScrollPane2.setViewportView(jList2);

        jButtonRemove.setText("remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonAdd.setText("add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("All components"));

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jButtonAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonRemove))
                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int[] indices = jList1.getSelectedIndices();
        for (int index : indices) {
            AxisChart2DComponent chartComponent = listChartComponentBundle.get(index).newAxisChart2DComponent();
            listInstalledChartComponent.add(chartComponent);
        }
        axisChart.repaintChartSurface();
}//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        int[] indices = jList2.getSelectedIndices();
        for (int index : indices) {
            AxisChart2DComponent chartComponent = listInstalledChartComponent.get(index);
            listInstalledChartComponent.remove(chartComponent);
        }
        axisChart.repaintChartSurface();
}//GEN-LAST:event_jButtonRemoveActionPerformed

    private void disactivate(AxisChart2DComponent chartComponent, int index) {
        displayStackImpl.remove(chartComponent);
        ((CheckList.Element) defaultListModel1.getElementAt(index)).isAvtive = false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[] indices = jList2.getSelectedIndices();
        for (int index : indices) {
            AxisChart2DComponent chartComponent = listInstalledChartComponent.get(index);
            disactivate(chartComponent, index);
        }
        jList2.repaint();
        axisChart.repaintChartSurface();
}//GEN-LAST:event_jButton1ActionPerformed

    private void activate(AxisChart2DComponent chartComponent, int index) {
        displayStackImpl.add(chartComponent);
        chartComponent.attachTo(axisChart);
        ((CheckList.Element) defaultListModel1.getElementAt(index)).isAvtive = true;

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int[] indices = jList2.getSelectedIndices();
        for (int index : indices) {
            AxisChart2DComponent chartComponent = listInstalledChartComponent.get(index);
            activate(chartComponent, index);
        }
        jList2.repaint();
        axisChart.repaintChartSurface();
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int index = jList2.getSelectedIndex();
        if (index == -1) {
            return;
        }
        AxisChart2DComponent component = listInstalledChartComponent.get(index);
        JFrame jFrame = component.getFrame();
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if (jFrame != null) {
            jFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "This component doesn't have any configuration panel.");
        }
}//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
