package ogla.label;

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.image.BufferedImage;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;

public class ConfigurationFrame extends javax.swing.JFrame {

    private Graphics2D gd = null;
    private DefaultComboBoxModel fontList = new DefaultComboBoxModel();

    public ConfigurationFrame() {
        initComponents();
        jComboBox3.setModel(fontList);
        for (String fontName : GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames()) {
            fontList.addElement(fontName);
        }
        Font font = UIManager.getDefaults().getFont(Font.SERIF);
        font = Font.decode(GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames()[0]);
        setFontSize(font.getSize());
        jComboBox1.setSelectedIndex(0);
    }

    public void setBufferedImage(BufferedImage bufferedImage) {
        this.gd = (Graphics2D) bufferedImage.getGraphics();
    }

    public void setFontSize(int size) {
        jSpinner1.setValue(size);
    }

    public int getFontSize() {
        return (Integer) jSpinner1.getValue();
    }

    public int getStyle() {
        return jComboBox5.getSelectedIndex();
    }
    private StringBuilder top = new StringBuilder();
    private StringBuilder bottom = new StringBuilder();
    private StringBuilder right = new StringBuilder();
    private StringBuilder left = new StringBuilder();
    private StringBuilder current = top;

    public StringBuilder activeBuilder() {
        String a = jComboBox1.getSelectedItem().toString();
        if (a.equals("Top")) {
            return top;
        } else if (a.equals("Bottom")) {
            return bottom;
        } else if (a.equals("Right")) {
            return right;
        } else if (a.equals("Left")) {
            return left;
        }
        return null;
    }

    public void setTop(String s) {
        this.top.append(s);
    }

    public String getTop() {
        return this.top.toString();
    }

    public void setBottom(String s) {
        this.bottom.append(s);
    }

    public String getBottom() {
        return this.bottom.toString();
    }

    public void setRight(String s) {
        this.right.append(s);
    }

    public String getRight() {
        return this.right.toString();
    }

    public void setLeft(String s) {
        this.left.append(s);
    }

    public String getLeft() {
        return this.left.toString();
    }

    public void clearBuffers() {
        this.top.delete(0, this.top.capacity());
        this.bottom.delete(0, this.bottom.capacity());
        this.right.delete(0, this.right.capacity());
        this.left.delete(0, this.left.capacity());
    }

    @Override
    public void dispose() {

        StringBuilder builder = activeBuilder();
        builder.delete(0, builder.capacity());
        builder.append(jTextArea1.getText());
        jTextArea1.setText("");
        super.dispose();
    }

    @Override
    public void setVisible(boolean b) {
        if (b == false) {
            StringBuilder builder = activeBuilder();
            builder.delete(0, builder.capacity());
            builder.append(jTextArea1.getText());
            jTextArea1.setText("");
        }
        super.setVisible(b);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jComboBox3 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox5 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jComboBox1 = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jToolBar1.add(jComboBox3);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(12, 1, 22, 1));
        jToolBar1.add(jSpinner1);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain", "Bold", "Italic" }));
        jToolBar1.add(jComboBox5);
        jToolBar1.add(jSeparator2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Left", "Right", "Bottom" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        StringBuilder builder = activeBuilder();
        current.append(jTextArea1.getText());
        jTextArea1.setText(builder.toString());
        builder.delete(0, builder.capacity());
        current = builder;
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
