package ogla.perspectiveplot;

import ogla.exdata.DataBlock;
import ogla.axischart3D.plugin.plotmanager.DataBlockConverter;
import ogla.axischart3D.plugin.plotmanager.DataBlockConverterToGrid;
import ogla.axischart3D.plugin.plotmanager.DataBlockConverterToModel;
import ogla.axischart3D.plugin.plotmanager.DataBlockConverterToPoints;
import ogla.axischart3D.plugin.plotmanager.Gradient;
import ogla.g3d.Perspective;
import ogla.g3d.Primitive;
import ogla.math.Vector3;
import ogla.g3d.Color;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

public class Frame extends javax.swing.JFrame {

    Vector3 viewerPosition = new Vector3();
    Vector3 scale = new Vector3();
    Perspective perspective;
    
    /** Creates new form Frame */
    public Frame(Vector3 viewerPosition, Perspective perspective) {
        initComponents();
        this.perspective = perspective;
        this.viewerPosition = viewerPosition;
        this.viewerPosition.set(0, 0, 500);
        perspective.setViewerPosition(viewerPosition);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jCheckBox2.setText("viewport");
        jCheckBox2.setFocusable(false);
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jCheckBox2);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner1.setEnabled(false);
        jToolBar1.add(jSpinner1);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner2.setEnabled(false);
        jToolBar1.add(jSpinner2);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(500.0f), null, null, Float.valueOf(1.0f)));
        jSpinner3.setEnabled(false);
        jToolBar1.add(jSpinner3);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator8);

        jCheckBox3.setText("scale");
        jCheckBox3.setFocusable(false);
        jCheckBox3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jCheckBox3);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        jSpinner4.setEnabled(false);
        jToolBar1.add(jSpinner4);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), null, Float.valueOf(1.0f)));
        jSpinner5.setEnabled(false);
        jToolBar1.add(jSpinner5);

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), null, Float.valueOf(1.0f)));
        jSpinner6.setEnabled(false);
        jToolBar1.add(jSpinner6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Number x = (Number) jSpinner1.getValue();
        Number y = (Number) jSpinner2.getValue();
        Number z = (Number) jSpinner3.getValue();
        this.viewerPosition.set(x.floatValue(), y.floatValue(), z.floatValue());
        perspective.setViewerPosition(viewerPosition);
        x = (Number) jSpinner4.getValue();
        y = (Number) jSpinner5.getValue();
        z = (Number) jSpinner6.getValue();
        this.scale.set(x.floatValue(), y.floatValue(), z.floatValue());
        perspective.setScale(scale);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        boolean b = jCheckBox2.isSelected();
        jSpinner1.setEnabled(b);
        jSpinner2.setEnabled(b);
        jSpinner3.setEnabled(b);
    }//GEN-LAST:event_jCheckBox2ItemStateChanged
    public static final String Absolute = "Absolute";
    public static final String Relative = "Relative";
    protected DefaultComboBoxModel defaultComboBoxModelColorProperties = new DefaultComboBoxModel();
    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        boolean b = jCheckBox3.isSelected();
        jSpinner4.setEnabled(b);
        jSpinner5.setEnabled(b);
        jSpinner6.setEnabled(b);

    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
