package ogla.plot.circle;

import ogla.axischart2D.AxisChart2D;
import ogla.axischart2D.plugin.plotmanager.AxisChart2DPlotManager;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class ConfigurationFrame extends javax.swing.JFrame {

    /** Creates new form ConfigurationFrame */
    public ConfigurationFrame(AxisChart2D axisChart2D, AxisChart2DPlotManager axisChart2DPlotManager,
            Properties properties) {
        initComponents();
        configurationPanel = new ConfigurationPanel(axisChart2D, axisChart2DPlotManager, properties);
        addPanel(configurationPanel);
    }

    public void addPanel(JPanel jPanel) {
        this.getContentPane().removeAll();
        this.getContentPane().add(jPanel, BorderLayout.CENTER);
        jPanel.setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.getContentPane().setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.setSize(jPanel.getPreferredSize().width, jPanel.getPreferredSize().height);
        this.getContentPane().invalidate();
        this.getContentPane().validate();
        this.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ConfigurationPanel configurationPanel = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
