/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ogla.chart;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import ogla.chart.gui.InternalFrame;

/**
 *
 * @author mmatula
 */
public class ChartPanel extends javax.swing.JPanel {

    private ChartSurface chartSurface = new ChartSurface();

    /**
     * Creates new form ChartPanel
     */
    public ChartPanel() {
        initComponents();
        jDesktopPane1.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    }

    protected JPopupMenu jPopupMenu = null;

    public void setPopup(JPopupMenu jPopupMenu) {
        this.jPopupMenu = jPopupMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (this.jPopupMenu != null) {
            jPopupMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    public ChartSurface getChartSurface() {
        return chartSurface;
    }

    public JDesktopPane getDesktop() {
        return jDesktopPane1;
    }

    private class PopupMenu extends JPopupMenu {

        private JMenuItem show = new JMenuItem("Show/refersh");
        private JMenuItem hide = new JMenuItem("Hide");
        private InternalFrame internalFrame;

        private class ShowAction implements ActionListener {

            public void actionPerformed(ActionEvent e) {
                boolean b = internalFrame.isVisible();
                internalFrame.setVisible(true);
                internalFrame.setIcon(false);
                if (!b) {
                    jDesktopPane1.setComponentZOrder(internalFrame, 0);
                }
                jDesktopPane1.repaint();
            }
        }

        private class HideAction implements ActionListener {

            public void actionPerformed(ActionEvent e) {
                internalFrame.setVisible(false);
                internalFrames.remove(internalFrame);
                jDesktopPane1.repaint();
            }
        }

        public PopupMenu(InternalFrame internalFrame) {
            super();
            this.internalFrame = internalFrame;
            show.addActionListener(new ShowAction());
            hide.addActionListener(new HideAction());
            this.add(show);
            this.add(hide);
        }
    }

    private class ActionListenerImpl implements ActionListener {

        protected InternalFrame internalFrame;
        protected PopupMenu popupMenu;
        protected JButton button;

        public ActionListenerImpl(PopupMenu popupMenu, JButton button) {
            this.internalFrame = popupMenu.internalFrame;
            this.popupMenu = popupMenu;
            this.button = button;
        }

        public void actionPerformed(ActionEvent e) {
            popupMenu.show(ChartPanel.this.jDesktopPane1, button.getX(), button.getY());
        }
    }
    private List<InternalFrame> internalFrames = new ArrayList<InternalFrame>();

    public void declareInternalFrameToToolBar(InternalFrame internalFrame) {
        PopupMenu popupMenu = new PopupMenu(internalFrame);
        JButton button = new JButton();
        ActionListenerImpl actionListenerImpl = new ActionListenerImpl(popupMenu, button);
        button.addActionListener(actionListenerImpl);
        button.setText(internalFrame.getTitle());
        this.jToolBar1.add(button);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
