name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sudo apt-get install libgtest-dev
      run: sudo apt-get install libgtest-dev
    - name: make clean
      run: make clean
    - name: make
      run: make
